---
# tasks file for pre-deploy
- name: repo
  template:
    src: apt-list.j2
    dest: /etc/apt/sources.list
  tags:
    - compute
    - apt
    - mon
    - osd

- name: apt update source list
  shell: apt update
  tags:
    - infra
    - compute
    - apt
    - mon    
    - osd
      ##- name: add proxy {{ proxy_url }} to 90curtin-aptprox file
      ##template:
      ## src: 90curtin-aptproxy.j2
      ##dest: /etc/apt/apt.conf.d/90curtin-aptproxy
      ##tags:
      ##- infra
      ##- compute
      ##- update-proxy
    
- name: Configure /etc/systemd/resolved.conf 
  template:
    src: resolved.conf.j2             
    dest: /etc/systemd/resolved.conf
  notify:
  - restart resolved
  tags:
    - infra
    - compute
    - resolved
    - mon
    - osd

- name: Install packages "{{ pkgs_install }}"
  apt:
    name: "{{ pkgs_install }}"
    state: present
  tags:
    - infra
    - compute
    - mon
    - osd

- name: remove packages "{{ pkgs_remove }}"
  apt:
    name: "{{ pkgs_remove }}"
    purge: yes
    state: absent
  tags:
    - infra
    - compute
    - mon
    - osd

- name: Update distro to the latest version
  apt:
    upgrade: dist
  tags:
    - infra
    - compute
    - mon
    - osd
 
- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
  tags:
    - infra
    - compute
    - mon
    - osd
  
- name: Set timezone to Asia/Tehran
  community.general.timezone:
    name: Asia/Tehran
  notify:
  - restart chronyd
  tags:
    - infra
    - compute
    - mon
    - osd

- name: Configure /etc/modules file 
  copy:
    src: modules
    dest: /etc/modules
  tags:
    - infra
    - compute
    - mon
    - osd

- name: Configure /etc/hosts file                                                              
  template:
    src: hosts.j2                    
    dest: /etc/hosts                                                            
  tags:
    - infra
    - compute

- name: Clean up  /openstack /etc/haproxy /etc/keepalived directory 
  file:
    path: "{{ item }}"
    state: absent
  with_items:  
    - "/openstack/"
    - "/etc/haproxy"
    - "/etc/keepalived/"
  tags: 
    - infra
    - compute


- name: clean LXC containers
  shell:
    cmd: "x=$(lxc-ls); for i in $x; do lxc-stop $i; lxc-destroy $i; done"
  tags:
    - infra
    
- name: Configure network for compute node
  template:
    src: compute-interfaces.j2
    dest: /etc/network/interfaces
  tags:
    - compute
    
- name: Configure network for infra node
  template:
    src: infra1-interfaces.j2
    dest: /etc/network/interfaces
  tags:
    - infra



- name: Configure network for ceph monitor node
  template:
    src: monitor-interfaces.j2
    dest: /etc/network/interfaces
  tags:
    - mon



- name: Configure network for ceph osd node
  template:
    src: ceph-interfaces.j2
    dest: /etc/network/interfaces
  tags:
    - osd




- name: Reboot a Linux machine 
  reboot:
    reboot_timeout: 1800
  tags: 
  - reboot
    #- name: Reboot after 5 seconds
    #  shell: ( sleep 5 ; reboot ) & 
    #  tags: 
    #  - compute
    #  - infra
